name: Compile-test-arm64

on:
  push:
    branches: [ "cuda" ]
  
  pull_request:
    branches: [ "cuda" ]

jobs:
  Compile-vins-fusion-amd64:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Start to Compile
      run: ./docker/scripts/compile.sh
    -
      name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: install.tar.gz
        path: install.tar.gz

